#include <iostream>
#include <exception.h>
#include <exception.cpp>
#include <testexception.cpp>
using namespace std;

int main()
{
    TestException();
    return 0;
}
